[package]
name = "turing-backend"
version = "0.1.0"
authors = [
    "James Dong <dong.james.sept14@gmail.com>",
]
description = "backend for tuRing group chat"
repository = "https://github.com/j-dong/tuRing"
readme = "README.md"
license = "MIT"

[dependencies]
"ring" = "*"
